fixed the pki enviroment and with a working certbot

diff --git a/ca-server b/ca-server
--- a/ca-server
+++ b/ca-server
@@ -3,25 +3,24 @@
 HOST=$1
 VAULT=ca
 
+/bin/vault-refresh $VAULT
+
 if [ ! -f /opt/pki-data/$VAULT.vhd ] ; then
  echo "[ERROR] Virtual hard disk file does not exist"
+ exit 99
 fi
 
 sudo cryptsetup status $VAULT.evhd
 if [ $? -eq 0 ] ;  then # check device exists
-    echo "[ERROR] Encrypted hard drive status is unknown"
-fi
-
-# Check that device is mounted
-if [ ! -f /opt/pki-data/ca.vhd ] ; then
- 
+ echo "[ERROR] Encrypted hard drive status is unknown"
+ exit 98
 fi
 
 easypki --root /mnt/$VAULT create --ca-name ca.gautier.local --expire 3650 --dns $HOST $HOST
 
-mkdir -p /mnt/$VAULT/public
-VAULT_PATH=/mnt/$VAULT/ca.gautier.local
-cat $VAULT_PATH/certs/$HOST.crt $VAULT_PATH/certs/ca.gautier.local.crt > $VAULT_PATH/public/$HOST.pem
-chmod +r-w $VAULT_PATH/public/$HOST.pem
+# mkdir -p /mnt/$VAULT/public
+# VAULT_PATH=/mnt/$VAULT/ca.gautier.local
+# cat $VAULT_PATH/certs/$HOST.crt $VAULT_PATH/certs/ca.gautier.local.crt > $VAULT_PATH/public/$HOST.pem
+# chmod +r-w $VAULT_PATH/public/$HOST.pem
 
-/bin/vault-refresh ca
+/bin/vault-refresh $VAULT
diff --git a/pki-setup b/pki-setup
--- a/pki-setup
+++ b/pki-setup
@@ -7,22 +7,38 @@
 # 4. Link the ca-root and ca together
 # finally unmount vault ca-root
 # refresh vault ca
+if [ -z $1 ] ; then
+ echo "[ERROR] Domain default is required for initial pki setup"
+ exit 99
+fi
+
+if [ -f /opt/pki-data/ca-root.vhd ] ; then
+ echo "[ERROR] CA-ROOT vault is already created"
+ exit 98
+fi
+
+if [ -f /opt/pki-data/ca.vhd ] ; then
+ echo "[ERROR] CA vault is already created"
+ exit 97
+fi
 
 vault-umount ca-root
 vault-setup ca-root
-# vault-mount ca-root
 date +%s > /mnt/ca-root/.last
 
 vault-umount ca
 vault-setup ca
-# vault-mount ca
 date +%s > /mnt/ca/.last
 
 # Create ca-root and ca
 DOMAIN=$1
+
+# Build CA
 easypki --root /mnt/ca-root create --filename root --ca "Personal Certificate Authority - $DOMAIN"
+# Build CA (Intermediate)
 easypki --root /mnt/ca-root create --ca-name root --filename ca.$DOMAIN --intermediate "Certificate Authority for ca.$DOMAIN"
 mv /mnt/ca-root/ca.$DOMAIN /mnt/ca/ca.$DOMAIN
 
 vault-umount ca-root
+
 
