Update for new working pki service

diff --git a/pki-create-client b/pki-create-client
--- a/pki-create-client
+++ b/pki-create-client
@@ -7,11 +7,14 @@ if [ -z $1 ] ; then
  exit 1
 fi
 
-MOUNT_POINT=/mnt/vault
-EXPORT_POINT=/opt/pki/outbox
+MOUNT_POINT="/mnt/vault"
+OUTBOX="/mnt/volumes/container/outbox"
+
+CA_KEY="$MOUNT_POINT/ca/ca.gautier.org/keys/ca.gautier.org.key"
+CA_CRT="$MOUNT_POINT/ca/ca.gautier.org/certs/ca.gautier.org.crt"
 
 KEYS="$MOUNT_POINT/clients/keys"
-CRTS="$MOUNT_POINT/clients/crts"
+CRTS="$MOUNT_POINT/clients/certs"
 CSRS="$MOUNT_POINT/clients/csrs"
 
 /usr/bin/vault-umount
@@ -19,28 +22,89 @@ CSRS="$MOUNT_POINT/clients/csrs"
 
 HOST=$1
 
+CLIENT_KEY="$KEYS/$HOST.key"
+CLIENT_CRT="$CRTS/$HOST.crt"
+CLIENT_CSR="$CSRS/$HOST.csr"
+CLIENT_PKG="$OUTBOX/$HOST.pfx"
+
 /bin/mountpoint -q $MOUNT_POINT
 if [ $? -eq 1 ] ; then
  echo "[ERROR] Vault is not mounted"
  exit 1
 fi
 
-if [ -f $KEYS/$HOST.key ] ; then
- echo"[ERROR] Key already exists for client($HOST)"
+if [ ! -d "$OUTBOX" ] ; then
+ echo"[ERROR] Outbox($OUTBOX) folder does not exist"
  exit 2
 fi
 
-if [ -f $EXPORT_POINT/$HOST.pfx ] ; then
- echo"[ERROR] Key/Cert package  already exists for client($HOST)"
- exit 2
+if [ ! -f "$CA_KEY" ] ; then
+ echo"[ERROR] CA Key($CA_KEY) file does not exist"
+ exit 3
 fi
 
-/usr/bin/openssl genrsa -des3 -out $KEYS/$HOST.key 4096
+if [ ! -f "$CA_CRT" ] ; then
+ echo"[ERROR] CA Certificate($CA_CRT) file does not exist"
+ exit 3
+fi
+
+if [ ! -d "$KEYS" ] ; then
+ echo"[ERROR] Keys($KEYS) folder does not exist"
+ exit 4
+fi
+
+if [ ! -d "$CRTS" ] ; then
+ echo"[ERROR] Certificates($CRTS) folder does not exist"
+ exit 4
+fi
+
+if [ ! -d "$CSRS" ] ; then
+ echo"[ERROR] Certificate Signing Requests($CSRS) folder does not exist"
+ exit 4
+fi
+
+if [ ! -d "$OUTBOX" ] ; then
+ echo"[ERROR] Export Point($EXPORT_POINT) folder does not exist"
+ exit 4
+fi
+
+if [ -f $CLIENT_PKG ] ; then
+  echo"[ERROR] Client package($CLIENT_PKG) already exists"
+ exit 5
+fi
+
+if [ -f $CLIENT_KEY ] ; then
+ echo"[ERROR] Client key($CLIENT_KEY) already exists"
+ exit 5
+fi
+
+if [ -f $CLIENT_CRT ] ; then
+ echo"[ERROR] Client certificate($CLIENT_CRT) already exists"
+ exit 5
+fi
+
+if [ -f $CLIENT_CSR ] ; then
+ echo"[ERROR] Client certificate signing request($CLIENT_CSR) already exists"
+ exit 5
+fi
+
+# /usr/bin/openssl genrsa -des3 -out /mnt/vault/clients/keys/saturn.gautier.org.key 4096
+#
+# /usr/bin/openssl req -new \
+#  -subj "/C=US/ST=North Carolina/L=Charlotte/O=Client Certificate(saturn.gautier.org)/OU=pki/CN=saturn.gautier.org" \
+# -key /mnt/vault/clients/keys/saturn.gautier.org.key -out /mnt/vault/clients/csrs/saturn.gautier.org.csr
+#
+# /usr/bin/openssl x509 -req -days 3650 -in /mnt/vault/clients/csrs/saturn.gautier.org.csr -CA /mnt/vault/ca/ca.gautier.org/certs/ca.gautier.org.crt -CAkey /mnt/vault/ca/ca.gautier.org/keys/ca.gautier.org.key -set_serial 01 -out /mnt/vault/clients/certs/saturn.gautier.org.crt
+#
+# /usr/bin/openssl pkcs12 -export -out /mnt/volumes/container/outbox/saturn.gautier.org.pfx -inkey /mnt/vault/clients/keys/saturn.gautier.org.key -in /mnt/vault/clients/certs/saturn.gautier.org.crt -certfile /mnt/vault/ca/ca.gautier.org/certs/ca.gautier.org.crt
+
+ 
+/usr/bin/openssl genrsa -des3 -out $CLIENT_KEY 4096
 /usr/bin/openssl req -new \
  -subj "/C=US/ST=North Carolina/L=Charlotte/O=Client Certificate($HOST)/OU=pki/CN=$HOST" \
- -key $KEYS/$HOST.key -out $CSRS/$HOST.csr
-/usr/bin/openssl x509 -req -days 3650 -in $CSRS/$HOST.csr -CA $CRTS/ca.client.crt -CAkey $KEYS/ca.client.key -set_serial 01 -out $CRTS/$HOST.crt
-/usr/bin/openssl pkcs12 -export -out $EXPORT_POINT/$HOST.pfx -inkey $KEYS/$HOST.key -in $CRTS/$HOST.crt -certfile $CRTS/ca.client.crt
+ -key $CLIENT_KEY -out $CLIENT_CSR
+/usr/bin/openssl x509 -req -days 3650 -in $CLIENT_CSR -CA $CA_CRT -CAkey $CA_KEY -set_serial 01 -out $CLIENT_CRT
+/usr/bin/openssl pkcs12 -export -out $CLIENT_PKG -inkey $CLIENT_KEY -in $CLIENT_CRT -certfile $CA_CRT
 
 /usr/bin/vault-umount
 
diff --git a/vault-mount b/vault-mount
--- a/vault-mount
+++ b/vault-mount
@@ -2,16 +2,19 @@
 
 # vault-mount: Opens the vault device (decrypts) and mounts to mount point.
 
-MOUNT_POINT=/mnt/vault
+MOUNT_POINT="/mnt/vault"
+VAULT_PATH="/mnt/volumes/container/vault.evhd"
 
+# If the mount point does not exist then create it.
 if [ ! -d $MOUNT_POINT ] ; then
  echo "[WARN] Creating mount point"
  /usr/bin/sudo /bin/mkdir -p $MOUNT_POINT
  /usr/bin/sudo /bin/chown pki:pki $MOUNT_POINT
 fi
 
-if [ ! -f "/opt/pki/vault.evhd" ] ; then
- echo "[ERROR] Vault(/opt/pki/vault.evhd) not found."
+# Make sure vault exists
+if [ ! -f "$VAULT_PATH" ] ; then
+ echo "[ERROR] Vault(/$VAULT_PATH) not found."
  exit 5
 fi
 
@@ -33,22 +36,24 @@ if [ ! $RTN -eq 4 ] ;  then
 fi
 
 # Open Vault
-/usr/bin/sudo /sbin/cryptsetup luksOpen /opt/pki/vault.evhd vault
+/usr/bin/sudo /sbin/cryptsetup luksOpen $VAULT_PATH vault
 if [ ! $? -eq 0 ] ;  then
- echo "[ERROR] Unable to open vault(/opt/pki/vault.evhd)."
+ echo "[ERROR] Unable to open vault($VAULT_PATH)."
  echo "- - - - - - - - - - - - - - - - - - - - - - - - - - - - -"
  ls -l /dev/mapper
  exit 8
 fi
 
-if [ ! -f "$MOUNT_POINT/.last" ] ; then
+/bin/mountpoint -q $MOUNT_POINT
+if [ $? -ne 0 ] ; then
  /usr/bin/sudo /bin/mount /dev/mapper/vault $MOUNT_POINT
- if [ ! $? -eq 0 ] ;  then
-  echo "[ERROR] Unable to mount vault($MOUNT_POINT)."
+ if [ $? -ne 0 ] ;  then
+  echo "[ERROR] Unable to mount($_TEST) vault($MOUNT_POINT)."
   exit 9
+ else
+    # Force all files in vault to be owned by container users
+    /usr/bin/sudo chown -R pki:pki $MOUNT_POINT
+    # Refresh the keep-alive ticker
+    /usr/bin/vault-refresh
  fi
- # Force all files in vault to be owned by container users
- /usr/bin/sudo chown -R pki:pki $MOUNT_POINT
- # Refresh the keep-alive ticker
- /usr/bin/vault-refresh
 fi
