Massive super simplification

diff --git a/vault-monitor b/vault-monitor
--- a/vault-monitor
+++ b/vault-monitor
@@ -1,84 +1,17 @@
 #!/bin/sh
 
-# Simple script to poll a file in the ca.vault that has the last accessed timestamp. If the file has not been updated 
-# within the coded timeout period then unmount the volume.
-# VAULT=$1
-# echo "Cleanup vault: $VAULT"
-# LAST_FILE=/opt/docker/pki/vaults/$VAULT.vault/.last
-# echo "File:$LAST_FILE"
-# TIMEOUT=$(((5 * 60)))
-# echo "Timeout:$TIMEOUT"
-# if [ -f "$LAST_FILE" ] ; then
-#     LAST_TIMESTAMP=$(cat "$LAST_FILE")
-#     CURRENT_TIMESTAMP=$(date +%s)
-#     echo "Current:$CURRENT_TIMESTAMP - Last:$LAST_TIMESTAMP"
-#     DELTA_TIMESTAMP=$((($CURRENT_TIMESTAMP - $LAST_TIMESTAMP)))
-#     echo "Delta:$DELTA_TIMESTAMP"
-#     if  [ 1 = $((($DELTA_TIMESTAMP > $TIMEOUT))) ] ; then
-#         echo "Vault '$VAULT' will be unmounted"
-#         /home/mada/Development/Scripts/umount-vault $VAULT        
-#     else
-#         echo "Vault '$VAULT' timeout has not been reached"
-#     fi
-# else
-#     echo "Vault '$VAULT' is not mounted"
-# fi
+# 2021-01-12 Massively simplified
 
-TIMEOUT=$(((5 * 60)))
-VAULT=$1
+if [ ! -f /mnt/pki/root/.last ] ; then
+  vault-umount # Not mounted so just clean up
+  exit 99 # Quit with exit code but do nothing because not mounted
+fi
 
-unmount_vault () {
-  mountpoint "/mnt/pki/$1"
-  if [ $? -eq 0 ] ; then
-    sudo umount "/mnt/pki/$1"
-  else
-    echo "Nothing to unmount"
-  fi
-    echo "Closing device $1"
-    if [ -e "/dev/mapper/$1" ] ; then # check device exists
-      sudo cryptsetup luksClose $1
-    else
-      echo "$1 virtual device not found"
-    fi
-}
-
-for mp in /mnt/pki/* ; do # loop through the moint points
-  v=${mp##*/}
-  mountpoint "/mnt/pki/$v"
-  if [ $? -eq 0 ] ; then
-    if [ -f "$mp/.last" ] ; then
-      LAST_TIMESTAMP=$(cat "$mp/.last")
-      CURRENT_TIMESTAMP=$(date +%s)
-      DELTA_TIMESTAMP=$((($CURRENT_TIMESTAMP - $LAST_TIMESTAMP)))
-      if [ 1 = $((($DELTA_TIMESTAMP > $TIMEOUT))) ] ; then
-        vault-umount $v
-      fi
-    fi
-  else
-    if [ -e "/dev/mapper/$v" ] ; then # check device exists
-      sudo cryptsetup luksClose $v
-    fi
-  fi
-
-  if [ -d $mp ] ; then
-    v=${mp##*/}
-    unmount_vault $v
-  fi
-done
-
- 
-# else
-#   unmount_vault $VAULT
-# fi
-
-# if [ -f "/opt/docker/pki/vaults/$VAULT.vault/.last" ] ; then
-#     sudo umount /opt/docker/pki/vaults/$VAULT.vault
-#     sudo cryptsetup luksClose /dev/mapper/$VAULT.crypt
-# else
-#     echo "Vault '$VAULT' is not mounted"
-# fi
-#  
-# for mp in /mnt/pki/* ; do # loop through the moint points 
-#    if [ -d $mp ] ; then
-#    fi
-# done
+MINUTES=3
+TIMEOUT=$((($MINUTES * 60)))
+LAST_TIMESTAMP=$(cat /mnt/pki/root/.last")
+CURRENT_TIMESTAMP=$(date +%s)
+DELTA_TIMESTAMP=$((($CURRENT_TIMESTAMP - $LAST_TIMESTAMP)))
+if [ 1 = $((($DELTA_TIMESTAMP > $TIMEOUT))) ] ; then
+  vault-umount $v
+fi
diff --git a/vault-mount b/vault-mount
--- a/vault-mount
+++ b/vault-mount
@@ -1,61 +1,48 @@
 #!/bin/sh
 
-
-mount_vault () {
-  name=$1
-  key="/home/pki/repo/$1.evd"
-  vault="/dev/mapper/$1"
-  mount="/mnt/pki/$1"
-  if [ ! -f $key ] ; then
-    echo "Key file ($1) not found in repository."
-  else
-    if [ ! -d $mount ] ; then 
-      echo "Mount point ($1) not found."
-    else
-      read -n4 -p "Decrypt and mount vault $name? (type capitalized 'yes' to confirm)> " confirm
-      case $confirm in
-      "YES") echo "Opening $key as $1" \
-              && sudo cryptsetup luksOpen $key $1 \
-              && echo "Mounting $name as $mount" \
-              && sudo mount "$vault" "$mount"
-             if [ $? -eq 0 ] ; then
-               echo "Successfully mounted $name."
-               date +%s > "$mount/.last"
-             else
-               echo "Failed with exit code $?."
-               echo "Attempting Rollback"
-               sudo umount "$mount"
-               sudo cryptsetup luksClose $name
-             fi
-        ;;
-      *) echo "]$confirm["
-         echo "Not mounting vault $name" 
-         exit 99 
-        ;;
-      esac
-    fi
-  fi
-}
+# 2021-01-12 Massive simplification
 
 if [ ! -d /home/pki/repo ] ; then
-  echo "key repository not configured."
-else
-  cd /home/pki/repo
-  if [ ! -d /home/pki/repo/.git ] ; then 
-    echo "No key repository setup"
-  else
-    echo "Updating ecrypted virtual drives"
-    git pull
-  fi
-  if [ -z $1 ] ; then
-    for p in /home/pki/keys/*.evd ; do # loop through the evd files 
-      f=${p%.evd}
-      v=${f##*/}
-      mount_vault $v
-    done
-  else
-    mount_vault $1
-  fi
+  echo "[ERROR] key repository not configured."
+  exit 99
+fi
+if [ ! -d /home/pki/repo/.git ] ; then 
+  echo "[ERROR] No key repository setup"
+  exit 98
+fi
+if [ ! -d /mnt/pki/root ] ; then
+  echo "[ERROR] No mount point found."
+  exit 97
+fi
+if [ ! -f /home/pki/repo/root.evd ] ; then
+  echo "[ERROR] root PKI encrypted virtual disk not found"
+  exit 96
 fi
 
-cd /home/pki # Reset to pki home directory
+
+echo "Updating ecrypted virtual drive in repository"
+CURRENT_DIR=$(pwd)
+cd /home/pki/repo
+git pull
+cd $CURRENT_DIR
+
+read -n4 -p "Decrypt and mount vault $name? (type capitalized 'yes' to confirm)> " confirm
+case $confirm in
+  "YES") echo "Decrypting /home/pki/repo/root.evd as root" \
+         && sudo cryptsetup luksOpen root /home/pki/repo/root.evd \
+         && echo "Mounting 'root' as /mnt/pki/root" \
+         && sudo mount /dev/mapper/root /mnt/pki/root
+         if [ $? -eq 0 ] ; then
+           echo "Successfully mounted root"
+           date +%s > "/mnt/pki/root/.last"
+         else
+           echo "Failed with exit code $?."
+           echo "Attempting Rollback"
+           sudo umount /mnt/pki/root
+           sudo cryptsetup luksClose root
+         fi
+  ;;
+  *) echo "Not mounting vault root"
+     exit 95
+  ;;
+esac
