This is a working version

diff --git a/vault-monitor b/vault-monitor
--- a/vault-monitor
+++ b/vault-monitor
@@ -1,17 +1,23 @@
 #!/bin/sh
 
-# 2021-01-12 Massively simplified
+# This script unmounts a vault that has not been updated in the last 5 minutes.  This
+# script is designed to run every 15 minutes
 
-if [ ! -f /mnt/pki/root/.last ] ; then
-  vault-umount # Not mounted so just clean up
-  exit 99 # Quit with exit code but do nothing because not mounted
-fi
+VAULT=$1
 
-MINUTES=3
-TIMEOUT=$((($MINUTES * 60)))
-LAST_TIMESTAMP=$(cat /mnt/pki/root/.last)
-CURRENT_TIMESTAMP=$(date +%s)
-DELTA_TIMESTAMP=$((($CURRENT_TIMESTAMP - $LAST_TIMESTAMP)))
-if [ 1 = $((($DELTA_TIMESTAMP > $TIMEOUT))) ] ; then
-  vault-umount
+# if [ ! -f /mnt/$VAULT/.last ] ; then
+# vault-umount $VAULT # Not mounted so just clean up
+# exit 99 # Quit with exit code but do nothing because not mounted
+# date +%s > /mnt/$VAULT/.last
+# fi
+
+if [ -f /mnt/$VAULT/.last ] ; then
+ MINUTES=3
+ TIMEOUT=$((($MINUTES * 60)))
+ LAST_TIMESTAMP=$(cat /mnt/$VAULT/.last)
+ CURRENT_TIMESTAMP=$(date +%s)
+ DELTA_TIMESTAMP=$((($CURRENT_TIMESTAMP - $LAST_TIMESTAMP)))
+ if [ 1 = $((($DELTA_TIMESTAMP > $TIMEOUT))) ] ; then
+  vault-umount $VAULT
+ fi
 fi
